env: TRAVIS_CI=true
language: c

compiler:
  - gcc
  - clang

install:
  - sudo apt-get update -qq
  # for unit tests
  - sudo apt-get install -y check
  # for static code analysis
  - sudo apt-get install -y cppcheck rats
  # for integration/regression tests
  - sudo apt-get install -y libtest-unit-perl libnet-ssh2-perl
  # for test code coverage
  - sudo apt-get install -y lcov
  - gem install coveralls-lcov

before_script:
  - cd ${TRAVIS_BUILD_DIR}
  - lcov --directory . --zerocounters

script:
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs cppcheck 2>&1
  # - find . -type f -name "*.c" -print | grep -v t\/ | xargs rats --language=c
  - git clone https://github.com/proftpd/proftpd.git
  - mkdir -p proftpd/contrib/mod_loiter/
  - cp -R t/ proftpd/contrib/mod_loiter/t/
  - cp *.[ch] proftpd/contrib/mod_loiter/
  - cp mod_loiter.* proftpd/contrib/mod_loiter/
  - cp Makefile.in proftpd/contrib/mod_loiter/
  - cp config* proftpd/contrib/mod_loiter/
  - cp install-sh proftpd/contrib/mod_loiter/
  - cd proftpd
  # First, a shared module build
  - ./configure --enable-devel=coverage --enable-dso --enable-tests --with-shared=mod_loiter
  - make
  # Last, a static build
  - make clean
  - ./configure --enable-devel=coverage --enable-tests --with-modules=mod_loiter
  - make
  - cd contrib/mod_loiter
  - make TEST_VERBOSE=1 check
  - make PROFTPD_TEST_BIN=${TRAVIS_BUILD_DIR}/proftpd/proftpd integration-tests
  - cd ../../

after_success:
  - cd ${TRAVIS_BUILD_DIR}
  # capture the test coverage info
  - lcov --ignore-errors gcov,source --base-directory ${TRAVIS_BUILD_DIR}/proftpd/contrib/mod_loiter --directory proftpd/contrib/mod_loiter --capture --output-file coverage.info
  # filter out system and test code
  - lcov --remove coverage.info 'api/*' 't/*' '/usr/*' --output-file coverage.info
  # debug before upload
  - lcov --list coverage.info
  # upload coverage info to coveralls
  - coveralls-lcov coverage.info
